using System.Collections.ObjectModel;

namespace ClinicApp.Models.TreatmentModels;

// Groups all TreatmentHistory records for one visit date into one card on TreatmentHistoryPage.
public class TreatmentVisitGroup
{
    public DateTime VisitDate { get; set; }

    public ObservableCollection<TreatmentHistory> Treatments { get; } = new();

    // Formatted visit date, or blank if unset.
    public string DateDisplay =>
        VisitDate == DateTime.MinValue
            ? string.Empty
            : VisitDate.ToString("MMM dd, yyyy");

    // Time of the first treatment in the visit.
    public string TimeDisplay
    {
        get
        {
            var first = Treatments.FirstOrDefault();
            if (first == null) return string.Empty;
            if (DateTime.TryParse(first.Timestamp, out var dt))
                return dt.ToString("hh:mm tt");
            return string.Empty;
        }
    }

    // Single-line "date · time" shown once per visit card, instead of separate Date/Time columns.
    public string DateTimeDisplay =>
        string.IsNullOrEmpty(TimeDisplay) ? DateDisplay : $"{DateDisplay} · {TimeDisplay}";

    // One row per treatment/service performed at this visit, each flagged with its position
    // so the first row can skip the divider that separates it from the ones after it.
    public List<TreatmentRowItem> Items =>
        Treatments.Select((t, i) => new TreatmentRowItem(t, isFirst: i == 0)).ToList();

    // Known auto-generated Notes templates written by BillingService/ApproveAppointment —
    // these just restate the condition/description and carry no new information.
    private static bool IsAutoGeneratedNote(string? notes) =>
        string.IsNullOrWhiteSpace(notes) ||
        notes.Equals("Service rendered", StringComparison.OrdinalIgnoreCase) ||
        notes.StartsWith("Condition applied:", StringComparison.OrdinalIgnoreCase) ||
        notes.StartsWith("Appointment:", StringComparison.OrdinalIgnoreCase);

    // The first genuine (non-auto-generated) note across this visit's treatments, shown once
    // for the whole card rather than repeated per row.
    public string SharedNotes =>
        Treatments
            .Select(t => t.Notes ?? string.Empty)
            .FirstOrDefault(n => !IsAutoGeneratedNote(n))
        ?? string.Empty;

    // Whether this visit has a genuine note to show.
    public bool HasNotes => !string.IsNullOrWhiteSpace(SharedNotes);

    // "N treatment(s)" summary text — kept for any other screen that still wants a count,
    // though the redesigned card itself no longer displays it.
    public string VisitTitle =>
        Treatments.Count == 1
            ? "1 treatment"
            : $"{Treatments.Count} treatments";
}

// One treatment/service row inside a visit card on TreatmentHistoryPage.
public class TreatmentRowItem
{
    private readonly TreatmentHistory _record;

    // Whether this is the first row in its visit card, so the divider above it can be hidden.
    public bool IsFirst { get; }

    // Wraps a single treatment record.
    public TreatmentRowItem(TreatmentHistory record, bool isFirst = false)
    {
        _record = record;
        IsFirst = isFirst;
    }

    // Falls back to Condition/ActionType when Description is blank (non-service tooth entries).
    public string Description =>
        !string.IsNullOrWhiteSpace(_record.Description)
            ? _record.Description
            : !string.IsNullOrWhiteSpace(_record.Condition)
                ? _record.Condition
                : _record.ActionType;

    // Tooth name if known, else "#N", else blank for general services.
    public string ToothDisplay
    {
        get
        {
            if (!string.IsNullOrWhiteSpace(_record.ToothName))
                return _record.ToothName;
            if (_record.ToothNumber > 0)
                return $"#{_record.ToothNumber}";
            return string.Empty;
        }
    }

    // Whether this row has a tooth to show (false for general services).
    public bool HasTooth => !string.IsNullOrWhiteSpace(ToothDisplay);

    // Same condition color used on the odontogram, so this row visually ties back to the chart.
    // NOTE: currently renders white/invisible for some conditions (e.g. Extraction, Filling) —
    // see ToothAwareServices.GetCondition(), which is returning strings that don't exactly
    // match the ConditionColors dictionary keys in DentalChartViewModel. Needs a source fix there.
    public Color ToothColor
    {
        get
        {
            try { return Color.FromArgb(_record.Color); }
            catch { return Color.FromArgb("#CBD5E1"); }
        }
    }
}
